import { LiveModule } from "../../components/live-console";

export default function Page() {
  return (
    <LiveModule
      consoleType="admin"
      eyebrow="OPERATIONS / DISPATCH"
      title="Trips & dispatch"
      copy="Live trip inventory and dispatch status for your assigned scope. Seat inventory is generated by the database as soon as a trip is created."
      table="trips"
      orderBy="departure_at"
      ascending
      watch={["bookings", "trip_seats"]}
      allowEdit
      columns={[
        { key: "departure_at", label: "Departure", format: "datetime" },
        { key: "arrival_at", label: "Arrival", format: "datetime" },
        { key: "gate", label: "Gate" },
        { key: "capacity", label: "Capacity", format: "mono" },
        { key: "seats_sold", label: "Sold", format: "mono" },
        { key: "status", label: "Status", format: "status" },
      ]}
      createLabel="Create trip"
      createFields={[
        { key: "organization_id", label: "Organization", required: true, reference: { table: "organizations", labelColumns: ["name"] } },
        { key: "branch_id", label: "Branch", required: true, reference: { table: "branches", labelColumns: ["name", "code"], filterBy: "organization_id" } },
        {
          key: "route_id",
          label: "Route",
          required: true,
          reference: {
            table: "routes",
            labelColumns: ["origin.city", "destination.city"],
            filterBy: "organization_id",
            select: "id,organization_id,origin:terminals!routes_origin_terminal_id_fkey(city),destination:terminals!routes_destination_terminal_id_fkey(city)",
          },
        },
        { key: "departure_at", label: "Departure", type: "datetime-local", required: true },
        { key: "arrival_at", label: "Arrival", type: "datetime-local", required: true },
        { key: "capacity", label: "Capacity", type: "number", required: true },
        { key: "fare", label: "Fare", type: "number", required: true },
        { key: "gate", label: "Gate" },
      ]}
      statusFlow={{
        rpc: "transition_trip_status",
        versionKey: "inventory_version",
        transitions: {
          scheduled: ["ready", "cancelled"],
          ready: ["boarding", "cancelled"],
          boarding: ["departed", "cancelled"],
          departed: ["arrived"],
          arrived: ["completed"],
        },
      }}
    />
  );
}
