"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { dateTime, errorMessage, one, peso } from "@/lib/format";
import { useLiveTables } from "@/lib/realtime";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";
import { EmptyState, LiveBadge, LoadingState, PageHeading, Status } from "./ui";

type Terminal = { id: string; name: string; city: string; province: string | null };
type TripResult = { trip_id: string; operator_name: string; origin_name: string; destination_name: string; departure_at: string; arrival_at: string; fare: number | string; capacity: number; available_seats: number };
type Seat = { seat_id: string; seat_code: string; seat_class: string; is_accessibility: boolean; seat_state: string };
type HoldRow = { id: string; trip_id: string; expires_at: string; trip_seats: { seat_code: string } | { seat_code: string }[] | null; trips: { fare: number | string; departure_at: string; arrival_at: string; gate: string | null; organizations: { name: string } | { name: string }[] | null; routes: { origin: { name: string; city: string } | { name: string; city: string }[] | null; destination: { name: string; city: string } | { name: string; city: string }[] | null } | { origin: { name: string; city: string } | { name: string; city: string }[] | null; destination: { name: string; city: string } | { name: string; city: string }[] | null }[] | null } | { fare: number | string; departure_at: string; arrival_at: string; gate: string | null; organizations: { name: string } | { name: string }[] | null; routes: { origin: { name: string; city: string } | { name: string; city: string }[] | null; destination: { name: string; city: string } | { name: string; city: string }[] | null } | { origin: { name: string; city: string } | { name: string; city: string }[] | null; destination: { name: string; city: string } | { name: string; city: string }[] | null }[] | null }[] | null };

export function TripSearch() {
  const router = useRouter();
  const [terminals, setTerminals] = useState<Terminal[]>([]);
  const [results, setResults] = useState<TripResult[]>([]);
  const [searched, setSearched] = useState(false);
  const [loading, setLoading] = useState(true);
  const [searching, setSearching] = useState(false);
  const [error, setError] = useState("");
  const [origin, setOrigin] = useState("");
  const [destination, setDestination] = useState("");
  const [travelDate, setTravelDate] = useState(new Date().toISOString().slice(0, 10));
  const [passengers, setPassengers] = useState(1);

  const loadTerminals = useCallback(async () => {
    const client = getSupabaseBrowserClient(); if (!client) return;
    const { data, error: queryError } = await client.from("terminals").select("id,name,city,province").eq("is_active", true).order("city");
    if (queryError) setError(queryError.message); else setTerminals((data ?? []) as Terminal[]);
    setLoading(false);
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => void loadTerminals(), 0); return () => window.clearTimeout(timer); }, [loadTerminals]);
  const live = useLiveTables(["trips", "trip_seats", "seat_holds"], () => { if (searched) void runSearch(); });

  async function runSearch(event?: FormEvent<HTMLFormElement>) {
    event?.preventDefault(); const client = getSupabaseBrowserClient(); if (!client || !origin || !destination) return;
    if (origin === destination) { setError("Choose two different terminals."); return; }
    setSearching(true); setError(""); setSearched(true);
    const { data, error: rpcError } = await client.rpc("search_available_trips", { origin_id: origin, destination_id: destination, travel_date: travelDate, passenger_count: passengers });
    if (rpcError) { setError(rpcError.message); setResults([]); } else setResults((data ?? []) as TripResult[]);
    setSearching(false);
  }

  function swap() { setOrigin(destination); setDestination(origin); }

  return <><PageHeading eyebrow="BOOK A JOURNEY" title="Where are you going?" copy="Search departures published by real VanGO operators. Availability updates while you’re viewing the page." action={<LiveBadge status={live} />} />
    <form className="search-panel" onSubmit={runSearch}><div className="search-route"><label className="field"><span>From</span><select value={origin} onChange={(event) => setOrigin(event.target.value)} required><option value="">Choose origin</option>{terminals.map((item) => <option value={item.id} key={item.id}>{item.city} · {item.name}</option>)}</select></label><button className="swap-button" type="button" aria-label="Swap origin and destination" onClick={swap}>⇄</button><label className="field"><span>To</span><select value={destination} onChange={(event) => setDestination(event.target.value)} required><option value="">Choose destination</option>{terminals.map((item) => <option value={item.id} key={item.id}>{item.city} · {item.name}</option>)}</select></label></div><div className="search-details"><label className="field"><span>Travel date</span><input type="date" min={new Date().toISOString().slice(0, 10)} value={travelDate} onChange={(event) => setTravelDate(event.target.value)} required /></label><label className="field"><span>Passengers</span><select value={passengers} onChange={(event) => setPassengers(Number(event.target.value))}>{Array.from({ length: 8 }, (_, index) => index + 1).map((value) => <option value={value} key={value}>{value} passenger{value === 1 ? "" : "s"}</option>)}</select></label><button className="primary-button search-button" disabled={searching || loading} type="submit">{searching ? "Searching…" : "Search live trips"}</button></div></form>
    {error ? <div className="form-alert error" role="alert">{error}</div> : null}{loading ? <LoadingState label="Loading active terminals…" /> : null}
    {!loading && !terminals.length ? <EmptyState title="No active terminals yet" copy="Trips will become searchable after an operator publishes terminals, routes, and schedules in VanGO." /> : null}
    {results.length ? <section className="trip-results"><div className="section-title"><div><span>AVAILABLE DEPARTURES</span><h2>{results.length} trip{results.length === 1 ? "" : "s"} found</h2></div><small>Prices are calculated again at checkout.</small></div>{results.map((trip) => <article className="trip-result" key={trip.trip_id}><div className="trip-time"><strong>{new Date(trip.departure_at).toLocaleTimeString("en-PH", { hour: "2-digit", minute: "2-digit" })}</strong><span>{dateTime(trip.departure_at).split(",")[0]}</span></div><div className="trip-route"><span>{trip.origin_name}</span><i /><b>{trip.destination_name}</b><small>{trip.operator_name} · arrives {new Date(trip.arrival_at).toLocaleTimeString("en-PH", { hour: "2-digit", minute: "2-digit" })}</small></div><div className="trip-capacity"><Status tone={trip.available_seats <= 5 ? "warning" : "success"}>{trip.available_seats} seats left</Status></div><div className="trip-fare"><small>FROM</small><strong>{peso(trip.fare)}</strong><span>per seat</span></div><button className="primary-button" type="button" onClick={() => router.push(`/user/seats?trip=${trip.trip_id}&passengers=${passengers}`)}>Choose seats</button></article>)}</section> : null}
    {searched && !searching && !results.length && !error ? <EmptyState title="No matching trips" copy="There are no published departures with enough available seats for this route and date. Try another date or passenger count." /> : null}
  </>;
}

export function SeatPicker() {
  const params = useSearchParams(); const router = useRouter();
  const tripId = params.get("trip") ?? ""; const count = Math.min(8, Math.max(1, Number(params.get("passengers") ?? 1)));
  const [seats, setSeats] = useState<Seat[]>([]); const [selected, setSelected] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { const client = getSupabaseBrowserClient(); if (!client || !tripId) { setLoading(false); return; } const { data, error: queryError } = await client.rpc("get_trip_seat_map", { target_trip_id: tripId }); if (queryError) setError(queryError.message); const rows = (data ?? []) as Seat[]; setSeats(rows); setSelected((current) => current.filter((code) => rows.some((seat) => seat.seat_code === code && seat.seat_state === "available"))); setLoading(false); }, [tripId]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const live = useLiveTables(["trip_seats", "seat_holds", "trips"], load);
  function toggle(seat: Seat) { if (seat.seat_state !== "available") return; setSelected((current) => current.includes(seat.seat_code) ? current.filter((code) => code !== seat.seat_code) : current.length < count ? [...current, seat.seat_code] : current); }
  async function hold() { const client = getSupabaseBrowserClient(); if (!client || selected.length !== count) return; setLoading(true); setError(""); const { data, error: rpcError } = await client.rpc("hold_trip_seats", { target_trip_id: tripId, seat_codes: selected, ttl_seconds: 600 }); if (rpcError) { setError(rpcError.message); await load(); setLoading(false); return; } router.push(`/user/checkout?hold=${(data as { hold_group: string }).hold_group}`); }
  return <><PageHeading eyebrow="STEP 1 OF 3" title={`Choose ${count} seat${count === 1 ? "" : "s"}`} copy="Available seats are loaded from the trip inventory. A selected seat is not reserved until you create the timed hold." action={<LiveBadge status={live} />} />{!tripId ? <EmptyState title="No trip selected" copy="Search for a departure first." action={<Link className="primary-button" href="/user/search">Find a trip</Link>} /> : null}{error ? <div className="form-alert error">{error}</div> : null}{loading ? <LoadingState label="Checking current seat availability…" /> : null}{!loading && tripId ? <div className="seat-layout"><div className="seat-legend"><span><i className="available" />Available</span><span><i className="selected" />Selected</span><span><i className="unavailable" />Unavailable</span><span><i className="accessible" />Accessibility</span></div><div className="vehicle"><div className="vehicle-front"><b>DRIVER</b><span>FRONT</span></div><div className="seat-grid">{seats.map((seat) => <button className={`seat ${selected.includes(seat.seat_code) ? "selected" : ""} ${seat.seat_state !== "available" ? "unavailable" : ""} ${seat.is_accessibility ? "accessible" : ""}`} type="button" key={seat.seat_id} disabled={seat.seat_state !== "available"} aria-pressed={selected.includes(seat.seat_code)} aria-label={`Seat ${seat.seat_code}, ${seat.seat_state}`} onClick={() => toggle(seat)}>{seat.seat_code}</button>)}</div></div><aside className="selection-summary"><span>YOUR SELECTION</span><h2>{selected.length ? selected.join(", ") : "No seats yet"}</h2><p>{selected.length} of {count} selected</p><button className="primary-button full" type="button" disabled={selected.length !== count || loading} onClick={() => void hold()}>Hold seats for 10 minutes</button><Link href="/user/search">Choose another trip</Link></aside></div> : null}</>;
}

export function Checkout() {
  const holdGroup = useSearchParams().get("hold") ?? ""; const router = useRouter();
  const [holds, setHolds] = useState<HoldRow[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [promo, setPromo] = useState(""); const [seconds, setSeconds] = useState(0);
  const load = useCallback(async () => { const client = getSupabaseBrowserClient(); if (!client || !holdGroup) { setLoading(false); return; } const { data, error: queryError } = await client.from("seat_holds").select("id,trip_id,expires_at,trip_seats(seat_code),trips(fare,departure_at,arrival_at,gate,organizations(name),routes(origin:terminals!routes_origin_terminal_id_fkey(name,city),destination:terminals!routes_destination_terminal_id_fkey(name,city)))").eq("hold_group", holdGroup).eq("status", "active").gt("expires_at", new Date().toISOString()); if (queryError) setError(queryError.message); setHolds((data ?? []) as unknown as HoldRow[]); setLoading(false); }, [holdGroup]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { const expires = holds[0]?.expires_at; if (!expires) return; const update = () => setSeconds(Math.max(0, Math.ceil((new Date(expires).getTime() - Date.now()) / 1000))); update(); const timer = window.setInterval(update, 1000); return () => window.clearInterval(timer); }, [holds]);
  useLiveTables(["seat_holds", "trips"], load);
  const trip = one(holds[0]?.trips); const route = one(trip?.routes); const origin = one(route?.origin); const destination = one(route?.destination); const operator = one(trip?.organizations); const subtotal = Number(trip?.fare ?? 0) * holds.length;
  async function release() { const client = getSupabaseBrowserClient(); if (!client || !holdGroup) return; await client.rpc("release_seat_hold", { target_hold_group: holdGroup }); router.replace("/user/search"); }
  async function confirm(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const client = getSupabaseBrowserClient(); if (!client || !holdGroup) return; setBusy(true); setError(""); try { const form = new FormData(event.currentTarget); const passengers = holds.map((hold, index) => { const rawAge = String(form.get(`age-${index}`) ?? ""); return { full_name: String(form.get(`name-${index}`) ?? "").trim(), mobile_e164: String(form.get(`mobile-${index}`) ?? "").trim(), age: rawAge ? Number(rawAge) : null, seat_code: one(hold.trip_seats)?.seat_code, eligibility_type: null }; }); const quoteResult = await client.rpc("quote_booking", { target_hold_group: holdGroup, promotion_code: promo.trim() || null }); if (quoteResult.error) throw quoteResult.error; const bookingResult = await client.rpc("confirm_booking", { target_quote_id: (quoteResult.data as { id: string }).id, passengers }); if (bookingResult.error) throw bookingResult.error; const booking = bookingResult.data as { booking_id: string; reference: string }; const payment = await client.rpc("complete_mock_payment", { target_booking_id: booking.booking_id }); if (payment.error) throw payment.error; router.replace(`/user/ticket?reference=${booking.reference}`); } catch (reason) { setError(errorMessage(reason)); setBusy(false); } }
  return <><PageHeading eyebrow="STEP 2 OF 3" title="Passenger details" copy="Complete the names for every held seat. The database validates the hold, quote, promotion, and booking before confirmation." action={holds.length ? <Status tone={seconds < 120 ? "danger" : "warning"}>{Math.floor(seconds / 60)}:{String(seconds % 60).padStart(2, "0")} remaining</Status> : undefined} />{error ? <div className="form-alert error">{error}</div> : null}{loading ? <LoadingState label="Loading your secure seat hold…" /> : null}{!loading && !holds.length ? <EmptyState title="Seat hold expired or missing" copy="Return to trip search and choose currently available seats again." action={<Link className="primary-button" href="/user/search">Find another trip</Link>} /> : null}{holds.length ? <form className="checkout-layout" onSubmit={confirm}><div className="checkout-main"><section className="journey-summary"><div><span>{origin?.city || "Origin"}</span><strong>→</strong><span>{destination?.city || "Destination"}</span></div><p>{origin?.name} to {destination?.name}</p><small>{trip ? dateTime(trip.departure_at) : ""} · {operator?.name} · Gate {trip?.gate || "TBA"}</small></section>{holds.map((hold, index) => <section className="passenger-form" key={hold.id}><div><b>{one(hold.trip_seats)?.seat_code}</b><span>{index === 0 ? "Lead passenger" : `Passenger ${index + 1}`}</span></div><label className="field"><span>Full name</span><input name={`name-${index}`} autoComplete={index === 0 ? "name" : "off"} required /></label><div className="field-row"><label className="field"><span>Mobile number</span><input name={`mobile-${index}`} type="tel" autoComplete={index === 0 ? "tel" : "off"} required /></label><label className="field compact"><span>Age</span><input name={`age-${index}`} type="number" min="0" max="120" required /></label></div></section>)}</div><aside className="checkout-aside"><section className="fare-summary"><span>FARE SUMMARY</span><p><small>{holds.length} seat{holds.length === 1 ? "" : "s"}</small><b>{peso(subtotal)}</b></p><label className="field"><span>Promo code (optional)</span><input value={promo} onChange={(event) => setPromo(event.target.value.toUpperCase())} maxLength={40} placeholder="VANGO CODE" /></label><div><small>Final total</small><strong>Calculated securely at confirmation</strong></div></section><section className="mock-notice"><span>SIMULATED PAYMENT</span><h3>No real money will be charged.</h3><p>The confirmation records a mock transaction only. No bank, wallet, or card is contacted.</p></section><button className="primary-button large full" type="submit" disabled={busy || seconds <= 0}>{busy ? "Confirming…" : "Confirm booking"}</button><button className="text-button full" type="button" onClick={() => void release()}>Release seats and cancel</button></aside></form> : null}</>;
}
