"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { dateOnly, dateTime, one, peso } from "@/lib/format";
import { useLiveTables } from "@/lib/realtime";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";
import { useAuth } from "../providers";
import { EmptyState, LiveBadge, LoadingState, PageHeading, Status, toneFor } from "./ui";

type TerminalInfo = { name: string; city: string };
type RouteInfo = { origin: TerminalInfo | TerminalInfo[] | null; destination: TerminalInfo | TerminalInfo[] | null };
type TripInfo = { departure_at: string; arrival_at: string; gate: string | null; organizations: { name: string } | { name: string }[] | null; routes: RouteInfo | RouteInfo[] | null };
type Booking = { id: string; reference: string; booking_status: string; payment_status: string; subtotal: number | string; fees: number | string; discount: number | string; total: number | string; created_at: string; trips: TripInfo | TripInfo[] | null };
type Refund = { id: string; booking_id: string; status: string; reason: string; amount: number | string; created_at: string };
type Notification = { id: string; type: string; title: string; body: string; action_path: string | null; read_at: string | null; created_at: string };

const bookingSelect = "id,reference,booking_status,payment_status,subtotal,fees,discount,total,created_at,trips(departure_at,arrival_at,gate,organizations(name),routes(origin:terminals!routes_origin_terminal_id_fkey(name,city),destination:terminals!routes_destination_terminal_id_fkey(name,city)))";

function BookingRoute({ booking }: { booking: Booking }) {
  const trip = one(booking.trips); const route = one(trip?.routes); const origin = one(route?.origin); const destination = one(route?.destination);
  return <><h3>{origin?.city || "Origin"} <span>→</span> {destination?.city || "Destination"}</h3><p>{trip ? dateTime(trip.departure_at) : "Departure unavailable"} · Gate {trip?.gate || "TBA"}</p></>;
}

export function UserHome() {
  const { profile } = useAuth();
  const [bookings, setBookings] = useState<Booking[]>([]); const [unread, setUnread] = useState(0); const [openCases, setOpenCases] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { const client = getSupabaseBrowserClient(); if (!client) return; const [bookingResult, notificationResult, caseResult] = await Promise.all([client.from("bookings").select(bookingSelect).order("created_at", { ascending: false }).limit(20), client.from("notifications").select("id", { count: "exact", head: true }).is("read_at", null), client.from("support_cases").select("id", { count: "exact", head: true }).not("status", "in", "(resolved,closed)")]); const failed = bookingResult.error ?? notificationResult.error ?? caseResult.error; if (failed) setError(failed.message); else { setBookings((bookingResult.data ?? []) as unknown as Booking[]); setUnread(notificationResult.count ?? 0); setOpenCases(caseResult.count ?? 0); } setLoading(false); }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const live = useLiveTables(["bookings", "notifications", "support_cases", "trips"], load);
  const upcoming = useMemo(() => bookings.filter((booking) => { const trip = one(booking.trips); return booking.booking_status === "confirmed" && trip && new Date(trip.departure_at) > new Date(); }).sort((first, second) => new Date(one(first.trips)!.departure_at).getTime() - new Date(one(second.trips)!.departure_at).getTime())[0], [bookings]);
  const confirmed = bookings.filter((booking) => booking.booking_status === "confirmed").length;
  return <><section className="home-hero"><div><span>GOOD DAY</span><h1>{profile?.full_name || "VanGO passenger"}</h1><p>Your real trips, tickets, and travel updates are organized here.</p></div><LiveBadge status={live} /><div className="hero-route-lines"><i /><i /><i /></div></section>{error ? <div className="form-alert error">{error}</div> : null}{loading ? <LoadingState /> : <><section className="home-stats"><Link href="/user/bookings"><span>BOOKINGS</span><strong>{bookings.length}</strong><small>{confirmed} currently confirmed</small></Link><Link href="/user/alerts"><span>UNREAD UPDATES</span><strong>{unread}</strong><small>Booking and trip notices</small></Link><Link href="/user/support"><span>OPEN SUPPORT</span><strong>{openCases}</strong><small>Cases awaiting closure</small></Link></section><section className="home-grid"><div><div className="section-title"><div><span>NEXT JOURNEY</span><h2>Upcoming trip</h2></div><Link href="/user/bookings">View all bookings</Link></div>{upcoming ? <article className="next-trip-card"><div className="next-trip-top"><span>CONFIRMED BOOKING</span><Status tone="success">{upcoming.booking_status}</Status></div><BookingRoute booking={upcoming} /><div className="next-trip-meta"><span><small>REFERENCE</small><b>{upcoming.reference}</b></span><span><small>MOCK PAYMENT</small><b>{upcoming.payment_status.replaceAll("_", " ")}</b></span><span><small>TOTAL</small><b>{peso(upcoming.total)}</b></span></div><Link className="primary-button" href={`/user/ticket?reference=${upcoming.reference}`}>Open e-ticket</Link></article> : <EmptyState title="No upcoming trip" copy="Book a published departure and your next confirmed journey will appear here." action={<Link className="primary-button" href="/user/search">Find a trip</Link>} />}</div><aside className="quick-actions"><div className="section-title"><div><span>QUICK ACTIONS</span><h2>What do you need?</h2></div></div><Link href="/user/search"><b>01</b><span><strong>Book another trip</strong><small>Search live routes and seats</small></span><em>→</em></Link><Link href="/user/bookings"><b>02</b><span><strong>Manage my bookings</strong><small>Tickets and refund requests</small></span><em>→</em></Link><Link href="/user/support"><b>03</b><span><strong>Message support</strong><small>Open or continue a case</small></span><em>→</em></Link></aside></section></>}</>;
}

function RefundRequest({ bookingId, onDone }: { bookingId: string; onDone: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const client = getSupabaseBrowserClient(); if (!client) return; setBusy(true); setError(""); const { error: rpcError } = await client.rpc("request_refund", { target_booking_id: bookingId, requested_reason: reason.trim() }); if (rpcError) setError(rpcError.message); else { setOpen(false); setReason(""); await onDone(); } setBusy(false); }
  if (!open) return <button className="secondary-button" type="button" onClick={() => setOpen(true)}>Request mock refund</button>;
  return <form className="inline-refund" onSubmit={submit}><label className="field"><span>Reason for refund</span><textarea minLength={4} maxLength={1000} value={reason} onChange={(event) => setReason(event.target.value)} required /></label><small>This creates a mock refund request only. No real currency moves.</small>{error ? <div className="form-alert error">{error}</div> : null}<div><button className="text-button" type="button" onClick={() => setOpen(false)}>Cancel</button><button className="primary-button" type="submit" disabled={busy}>{busy ? "Sending…" : "Submit request"}</button></div></form>;
}

export function UserBookings() {
  const [rows, setRows] = useState<Booking[]>([]); const [refunds, setRefunds] = useState<Refund[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [filter, setFilter] = useState("all");
  const load = useCallback(async () => { const client = getSupabaseBrowserClient(); if (!client) return; const [bookingResult, refundResult] = await Promise.all([client.from("bookings").select(bookingSelect).order("created_at", { ascending: false }), client.from("refunds").select("id,booking_id,status,reason,amount,created_at").order("created_at", { ascending: false })]); const failed = bookingResult.error ?? refundResult.error; if (failed) setError(failed.message); else { setRows((bookingResult.data ?? []) as unknown as Booking[]); setRefunds((refundResult.data ?? []) as Refund[]); } setLoading(false); }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]); const live = useLiveTables(["bookings", "refunds", "trips"], load);
  const filtered = rows.filter((row) => filter === "all" || row.booking_status === filter);
  return <><PageHeading eyebrow="MY TRAVEL" title="Bookings" copy="Every card is loaded from your own Supabase-protected booking history." action={<LiveBadge status={live} />} /><div className="filter-tabs" role="group" aria-label="Filter bookings">{["all", "confirmed", "pending", "completed", "cancelled"].map((value) => <button className={filter === value ? "active" : ""} type="button" key={value} onClick={() => setFilter(value)}>{value}</button>)}</div>{error ? <div className="form-alert error">{error}</div> : null}{loading ? <LoadingState /> : null}<div className="booking-grid">{filtered.map((booking) => { const refund = refunds.find((item) => item.booking_id === booking.id); const trip = one(booking.trips); const operator = one(trip?.organizations); return <article className="booking-card" key={booking.id}><div className="booking-card-head"><div><span>{booking.reference}</span><Status tone={toneFor(booking.booking_status)}>{booking.booking_status}</Status></div><strong>{peso(booking.total)}</strong></div><BookingRoute booking={booking} /><div className="booking-details"><span><small>OPERATOR</small><b>{operator?.name || "VanGO operator"}</b></span><span><small>PAYMENT</small><b>{booking.payment_status.replaceAll("_", " ")}</b></span><span><small>BOOKED</small><b>{dateOnly(booking.created_at)}</b></span></div>{refund ? <div className="refund-status"><span>MOCK REFUND</span><Status tone={toneFor(refund.status)}>{refund.status}</Status><p>{refund.reason}</p></div> : null}<div className="booking-actions"><Link className="primary-button" href={`/user/ticket?reference=${booking.reference}`}>View e-ticket</Link>{!refund && ["paid", "partially_refunded"].includes(booking.payment_status) ? <RefundRequest bookingId={booking.id} onDone={load} /> : null}</div></article>; })}</div>{!loading && !filtered.length && !error ? <EmptyState title={rows.length ? "No bookings in this filter" : "No bookings yet"} copy={rows.length ? "Choose another status to see your other bookings." : "Search a live departure and reserve your first VanGO trip."} action={!rows.length ? <Link className="primary-button" href="/user/search">Find a trip</Link> : undefined} /> : null}</>;
}

export function UserTicket() {
  const reference = useSearchParams().get("reference") ?? ""; const [booking, setBooking] = useState<Booking | null>(null); const [passengers, setPassengers] = useState<Array<{ id: string; full_name: string; seat_code: string; mobile_e164: string | null }>>([]); const [loading, setLoading] = useState(Boolean(reference)); const [error, setError] = useState("");
  const load = useCallback(async () => { const client = getSupabaseBrowserClient(); if (!client || !reference) { setLoading(false); return; } const bookingResult = await client.from("bookings").select(bookingSelect).eq("reference", reference).maybeSingle(); if (bookingResult.error) { setError(bookingResult.error.message); setLoading(false); return; } const current = bookingResult.data as unknown as Booking | null; setBooking(current); if (current) { const passengerResult = await client.from("booking_passengers").select("id,full_name,seat_code,mobile_e164").eq("booking_id", current.id).order("seat_code"); if (passengerResult.error) setError(passengerResult.error.message); else setPassengers(passengerResult.data ?? []); } setLoading(false); }, [reference]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]); useLiveTables(["bookings", "booking_passengers", "trips"], load);
  if (!reference) return <EmptyState title="No booking selected" copy="Open an e-ticket from your booking history." action={<Link className="primary-button" href="/user/bookings">My bookings</Link>} />;
  if (loading) return <LoadingState label="Loading your e-ticket…" />;
  if (error) return <div className="form-alert error">{error}</div>;
  if (!booking) return <EmptyState title="Ticket not found" copy="This booking is not available to the signed-in account." action={<Link className="primary-button" href="/user/bookings">My bookings</Link>} />;
  const trip = one(booking.trips); const route = one(trip?.routes); const origin = one(route?.origin); const destination = one(route?.destination); const operator = one(trip?.organizations);
  return <><PageHeading eyebrow="STEP 3 OF 3" title="Your e-ticket" copy="Keep this page ready and present the booking reference at the terminal." /><article className="ticket"><header><div><span>VANGO E-TICKET</span><strong>{booking.reference}</strong></div><Status tone={toneFor(booking.booking_status)}>{booking.booking_status}</Status></header><section className="ticket-route"><div><small>FROM</small><h2>{origin?.city || "Origin"}</h2><p>{origin?.name}</p></div><div className="ticket-line"><i /><span>VANGO</span><i /></div><div><small>TO</small><h2>{destination?.city || "Destination"}</h2><p>{destination?.name}</p></div></section><section className="ticket-meta"><span><small>DEPARTURE</small><b>{trip ? dateTime(trip.departure_at) : "—"}</b></span><span><small>OPERATOR</small><b>{operator?.name || "VanGO operator"}</b></span><span><small>GATE</small><b>{trip?.gate || "TBA"}</b></span><span><small>MOCK PAYMENT</small><b>{booking.payment_status.replaceAll("_", " ")}</b></span></section><section className="ticket-passengers"><div className="section-title"><div><span>PASSENGERS</span><h2>{passengers.length} traveler{passengers.length === 1 ? "" : "s"}</h2></div></div>{passengers.map((passenger) => <div key={passenger.id}><span><small>NAME</small><strong>{passenger.full_name}</strong></span><span><small>SEAT</small><b>{passenger.seat_code}</b></span></div>)}</section><footer><div><span>BOOKING ID</span><code>{booking.id}</code></div><strong>{peso(booking.total)}</strong></footer></article><section className="mock-notice ticket-notice"><span>SIMULATED RECEIPT</span><h3>No real money was charged.</h3><p>This ticket was confirmed through VanGO’s mock payment workflow.</p></section><div className="ticket-actions"><Link className="secondary-button" href="/user/bookings">Back to bookings</Link><button className="primary-button" type="button" onClick={() => window.print()}>Print ticket</button></div></>;
}

export function UserAlerts() {
  const [rows, setRows] = useState<Notification[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { const client = getSupabaseBrowserClient(); if (!client) return; const { data, error: queryError } = await client.from("notifications").select("id,type,title,body,action_path,read_at,created_at").order("created_at", { ascending: false }); if (queryError) setError(queryError.message); else setRows((data ?? []) as Notification[]); setLoading(false); }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]); const live = useLiveTables(["notifications"], load);
  async function markRead(id: string) { const client = getSupabaseBrowserClient(); if (!client) return; await client.from("notifications").update({ read_at: new Date().toISOString() }).eq("id", id); await load(); }
  async function markAll() { const client = getSupabaseBrowserClient(); if (!client) return; await client.from("notifications").update({ read_at: new Date().toISOString() }).is("read_at", null); await load(); }
  return <><PageHeading eyebrow="TRAVEL UPDATES" title="Notifications" copy="Booking confirmations, trip changes, and support updates for your account." action={<div className="heading-actions"><LiveBadge status={live} />{rows.some((item) => !item.read_at) ? <button className="secondary-button" type="button" onClick={() => void markAll()}>Mark all read</button> : null}</div>} />{error ? <div className="form-alert error">{error}</div> : null}{loading ? <LoadingState /> : null}<div className="notification-list">{rows.map((item) => <article className={item.read_at ? "" : "unread"} key={item.id}><i /><div><span>{item.type.replaceAll("_", " ")}</span><h2>{item.title}</h2><p>{item.body}</p><small>{dateTime(item.created_at)}</small><div>{item.action_path ? <Link className="primary-button small" href={item.action_path.replace("/passenger", "/user")}>Open</Link> : null}{!item.read_at ? <button className="text-button" type="button" onClick={() => void markRead(item.id)}>Mark as read</button> : null}</div></div></article>)}</div>{!loading && !rows.length && !error ? <EmptyState title="You’re all caught up" copy="New booking, trip, and support updates will appear here." /> : null}</>;
}

export function UserProfile() {
  const { profile, user, refreshProfile, signOut } = useAuth(); const [busy, setBusy] = useState(false); const [passwordBusy, setPasswordBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const client = getSupabaseBrowserClient(); if (!client || !user) return; const form = new FormData(event.currentTarget); setBusy(true); setError(""); setNotice(""); const { error: updateError } = await client.from("profiles").update({ full_name: String(form.get("full_name") ?? "").trim(), mobile_e164: String(form.get("mobile_e164") ?? "").trim() || null }).eq("id", user.id); if (updateError) setError(updateError.message); else { await refreshProfile(); setNotice("Profile saved successfully."); } setBusy(false); }
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const client = getSupabaseBrowserClient(); if (!client) return; const form = new FormData(event.currentTarget); const password = String(form.get("password") ?? ""); const confirmation = String(form.get("confirmation") ?? ""); setError(""); setNotice(""); if (password !== confirmation) { setError("The new passwords do not match."); return; } setPasswordBusy(true); const { error: updateError } = await client.auth.updateUser({ password }); if (updateError) setError(updateError.message); else { event.currentTarget.reset(); setNotice("Password updated successfully."); } setPasswordBusy(false); }
  return <><PageHeading eyebrow="MY ACCOUNT" title="Profile & security" copy="Manage the passenger details attached to your signed-in Supabase account." />{error ? <div className="form-alert error" role="alert">{error}</div> : null}{notice ? <div className="form-alert success" role="status">{notice}</div> : null}<div className="profile-layout"><form className="profile-card" onSubmit={save}><div className="profile-avatar">{(profile?.full_name || user?.email || "V").split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase()}</div><h2>{profile?.full_name || "Complete your profile"}</h2><p>{user?.email}</p><label className="field"><span>Full name</span><input name="full_name" defaultValue={profile?.full_name ?? ""} autoComplete="name" required /></label><label className="field"><span>Mobile number</span><input name="mobile_e164" defaultValue={profile?.mobile_e164 ?? ""} type="tel" autoComplete="tel" placeholder="+63" /></label><button className="primary-button full" disabled={busy} type="submit">{busy ? "Saving…" : "Save profile"}</button></form><aside className="account-panel"><section><span>ACCOUNT STATUS</span><Status tone={profile?.account_status === "active" ? "success" : "danger"}>{profile?.account_status || "active"}</Status><p>Your profile is protected by Supabase authentication and Row Level Security.</p></section><section><span>PRIVACY</span><h3>Only your records are visible.</h3><p>Bookings, notifications, seat holds, support cases, and tickets are filtered by your authenticated user ID in the database.</p></section><form className="password-form" onSubmit={changePassword}><span>SECURITY</span><h3>Change password</h3><label className="field"><span>New password</span><input name="password" type="password" minLength={8} autoComplete="new-password" required /></label><label className="field"><span>Confirm new password</span><input name="confirmation" type="password" minLength={8} autoComplete="new-password" required /></label><button className="secondary-button full" disabled={passwordBusy} type="submit">{passwordBusy ? "Updating…" : "Update password"}</button></form><button className="secondary-button danger full" type="button" onClick={() => void signOut()}>Sign out on this device</button></aside></div></>;
}
